image: debian:12

stages:
  - test

test:
  stage: test
  before_script:
    - apt-get -q update
    - apt-get -y -q install unzip wget
  script:
    - mkdir -p test/image/
    - mv build/openponk-class-editor-*.zip test/image/openponk.zip
    - cd test/
    - mkdir pharo/
    - cd pharo/
    - wget -q -O pharo.zip 'https://files.pharo.org/get-files/120/pharo-vm-Linux-x86_64-stable.zip'
    - unzip -q pharo.zip
    - cd ../image/
    - unzip -q openponk.zip
    - cd ../
    - "./pharo/bin/pharo --headless image/openponk-class-editor.image eval --save \"Metacello new baseline: 'Moco'; repository: 'tonel://../src'; load.\""
    - mv ../build/test.sh ./
    - ./test.sh
