name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: |
          mkdir test/
          mv build/openponk-class-editor-linux-76c3099.zip test/openponk.zip
          cd test/
          unzip -q openponk.zip
          cd openponk-class-editor-linux/
          ./pharo/bin/pharo --headless image/openponk-class-editor.image eval --save "Metacello new baseline: 'Moco'; repository: 'tonel://../../src'; load."
          mv ../../build/test.sh ./
          ./test.sh
