name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: |
          mkdir -p test/image/
          mv build/openponk-class-editor-*.zip test/image/openponk.zip
          cd test/
          mkdir pharo/
          cd pharo/
          wget -q -O pharo.zip 'https://files.pharo.org/get-files/110/pharo-vm-Linux-x86_64-stable.zip'
          unzip -q pharo.zip
          cd ../image/
          unzip -q openponk.zip
          cd ../
          ./pharo/bin/pharo --headless image/openponk-class-editor.image eval --save "Metacello new baseline: 'Moco'; repository: 'tonel://../src'; load."
          mv ../build/test.sh ./
          ./test.sh
